"""
Acceptance tests for Feature 9: CLI Feature Authoring.

These tests describe the intended CLI behavior for feature/scenario authoring.

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from __future__ import annotations

from pathlib import Path

from click.testing import CliRunner

from specleft import specleft
from specleft.cli.main import cli
from specleft.utils.history import load_feature_history
from conftest import FeatureFiles

# =============================================================================
# Feature: Feature 9: CLI Feature Authoring
# ID: feature-9-cli-feature-authoring
# priority: high
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="feature-9-cli-feature-authoring",
    scenario_id="create-feature-file-from-cli",
)
def test_create_feature_file_from_cli(
    feature_9_cli_authoring: tuple[CliRunner, Path, FeatureFiles],
) -> None:
    """Create feature file from CLI

    Priority: critical
    """
    _runner, _workspace, _files = feature_9_cli_authoring

    with specleft.step("Given no feature file exists for the requested feature id"):
        feature_file = Path("features/feature-cli-history.md")
        assert not feature_file.exists()

    with specleft.step("When specleft features add is executed with an id and title"):
        result = _runner.invoke(
            cli,
            [
                "features",
                "add",
                "--id",
                "cli-history",
                "--title",
                "CLI History",
            ],
        )
        assert result.exit_code == 0, result.output

    with specleft.step("And a history entry is recorded for feature creation"):
        entries = load_feature_history("cli-history")
        assert entries
        assert entries[-1]["action"] == "feature-created"

    with specleft.step(
        "Then a new feature markdown file is created with a scenario tag window"
    ):
        assert feature_file.exists()
        content = feature_file.read_text()
        assert "<!-- specleft:scenario-add -->" in content


@specleft(
    feature_id="feature-9-cli-feature-authoring",
    scenario_id="reject-invalid-feature-ids",
)
def test_reject_invalid_feature_ids(
    feature_9_cli_authoring: tuple[CliRunner, Path, FeatureFiles],
) -> None:
    """Reject invalid feature ids

    Priority: high
    """
    _runner, _workspace, _files = feature_9_cli_authoring

    with specleft.step("Given a feature id that contains uppercase or spaces"):
        feature_file = Path("features/feature-Bad-Id.md")
        assert not feature_file.exists()

    with specleft.step("When specleft features add is executed"):
        result = _runner.invoke(
            cli,
            [
                "features",
                "add",
                "--id",
                "Bad Id",
                "--title",
                "Bad Id",
            ],
        )
        assert result.exit_code == 1, result.output

    with specleft.step("And no history entry is recorded"):
        entries = load_feature_history("Bad Id")
        assert entries == []

    with specleft.step(
        "Then the command exits with a validation error and no file is written"
    ):
        assert "Feature ID must match" in result.output
        assert not feature_file.exists()


@specleft(
    feature_id="feature-9-cli-feature-authoring",
    scenario_id="append-scenario-to-feature-file",
)
def test_append_scenario_to_feature_file(
    feature_9_cli_authoring: tuple[CliRunner, Path, FeatureFiles],
) -> None:
    """Append scenario to feature file

    Priority: critical
    """
    _runner, _workspace, _files = feature_9_cli_authoring

    with specleft.step(
        "Given a feature markdown file exists with a scenario tag window"
    ):
        seed = _runner.invoke(
            cli,
            [
                "features",
                "add",
                "--id",
                "cli-history",
                "--title",
                "CLI History",
            ],
        )
        assert seed.exit_code == 0, seed.output

    with specleft.step(
        "When specleft features add-scenario is executed with a title and steps"
    ):
        result = _runner.invoke(
            cli,
            [
                "features",
                "add-scenario",
                "--feature",
                "cli-history",
                "--title",
                "Append scenario",
                "--step",
                "Given a scenario",
                "--step",
                "When appended",
                "--step",
                "Then it is added",
            ],
            input="n\n",
        )
        assert result.exit_code == 0, result.output

    with specleft.step("And a history entry is recorded for the scenario add"):
        entries = load_feature_history("cli-history")
        assert entries
        assert entries[-1]["action"] == "scenario-added"

    with specleft.step("Then the scenario is appended within the tag window"):
        content = Path("features/feature-cli-history.md").read_text()
        assert "### Scenario: Append scenario" in content


@specleft(
    feature_id="feature-9-cli-feature-authoring",
    scenario_id="reject-add-scenario-when-feature-missing",
)
def test_reject_add_scenario_when_feature_missing(
    feature_9_cli_authoring: tuple[CliRunner, Path, FeatureFiles],
) -> None:
    """Reject add-scenario when feature missing

    Priority: high
    """
    _runner, _workspace, _files = feature_9_cli_authoring

    with specleft.step("Given no feature markdown file exists for the requested id"):
        missing_path = Path("features/feature-missing-feature.md")
        assert not missing_path.exists()

    with specleft.step("When specleft features add-scenario is executed"):
        result = _runner.invoke(
            cli,
            [
                "features",
                "add-scenario",
                "--feature",
                "missing-feature",
                "--title",
                "Missing feature",
            ],
        )
        assert result.exit_code == 1, result.output

    with specleft.step("And no history entry is recorded"):
        entries = load_feature_history("missing-feature")
        assert entries == []

    with specleft.step("Then the command exits with an error and no file is written"):
        assert "Feature file not found" in result.output


@specleft(
    feature_id="feature-9-cli-feature-authoring",
    scenario_id="reject-interactive-mode-without-a-tty",
)
def test_reject_interactive_mode_without_a_tty(
    feature_9_cli_authoring: tuple[CliRunner, Path, FeatureFiles],
) -> None:
    """Reject interactive mode without a TTY

    Priority: medium
    """
    _runner, _workspace, _files = feature_9_cli_authoring

    with specleft.step("Given interactive mode is requested without a terminal"):
        pass

    with specleft.step("When specleft features add or add-scenario is executed"):
        result = _runner.invoke(
            cli,
            [
                "features",
                "add",
                "--interactive",
            ],
        )
        assert result.exit_code == 1, result.output

    with specleft.step("And no history entry is recorded"):
        entries = load_feature_history("interactive")
        assert entries == []

    with specleft.step("Then the command exits with a helpful error message"):
        assert "Interactive mode requires a terminal" in result.output

    with specleft.step("And no history entry is recorded"):
        entries = load_feature_history("interactive")
        assert entries == []


@specleft(
    feature_id="feature-9-cli-feature-authoring",
    scenario_id="reject-skeleton-generation-without-steps",
)
def test_reject_skeleton_generation_without_steps(
    feature_9_cli_authoring: tuple[CliRunner, Path, FeatureFiles],
) -> None:
    """Reject skeleton generation without steps

    Priority: medium
    """
    _runner, _workspace, _files = feature_9_cli_authoring

    with specleft.step("Given a scenario is created without steps"):
        seed = _runner.invoke(
            cli,
            [
                "features",
                "add",
                "--id",
                "cli-history",
                "--title",
                "CLI History",
            ],
        )
        assert seed.exit_code == 0, seed.output

    with specleft.step(
        "When specleft features add-scenario is executed with --add-test skeleton"
    ):
        result = _runner.invoke(
            cli,
            [
                "features",
                "add-scenario",
                "--feature",
                "cli-history",
                "--title",
                "Scenario no steps",
                "--add-test",
                "skeleton",
            ],
        )
        assert result.exit_code == 1, result.output

    with specleft.step("And no history entry is recorded"):
        entries = load_feature_history("cli-history")
        assert not any(entry["action"] == "scenario-added" for entry in entries)

    with specleft.step(
        "Then the command reports that steps are required for skeleton generation"
    ):
        assert "No steps found for test skeleton" in result.output


@specleft(
    feature_id="feature-9-cli-feature-authoring",
    scenario_id="preview-test-content-for-a-scenario",
)
def test_preview_test_content_for_a_scenario(
    feature_9_cli_authoring: tuple[CliRunner, Path, FeatureFiles],
) -> None:
    """Preview test content for a scenario

    Priority: low
    """
    _runner, _workspace, _files = feature_9_cli_authoring

    with specleft.step("Given a scenario is added with steps"):
        seed = _runner.invoke(
            cli,
            [
                "features",
                "add",
                "--id",
                "cli-history",
                "--title",
                "CLI History",
            ],
        )
        assert seed.exit_code == 0, seed.output

    with specleft.step(
        "When specleft features add-scenario is executed with --preview-test"
    ):
        result = _runner.invoke(
            cli,
            [
                "features",
                "add-scenario",
                "--feature",
                "cli-history",
                "--title",
                "Scenario preview",
                "--step",
                "Given a preview step",
                "--preview-test",
            ],
        )
        assert result.exit_code == 0, result.output

    with specleft.step("And a history entry is recorded for the scenario add"):
        entries = load_feature_history("cli-history")
        assert entries
        assert entries[-1]["action"] == "scenario-added"

    with specleft.step("Then the generated test preview is printed to stdout"):
        assert "Test preview:" in result.output
