# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 SpecLeft Contributors

"""Draft spec markdown writer for discovery phase 2."""

from __future__ import annotations

from pathlib import Path

from specleft.discovery.models import DraftFeature, DraftScenario
from specleft.schema import SpecStep
from specleft.utils.feature_writer import (
    generate_feature_id,
    generate_scenario_id,
    validate_feature_id,
    validate_scenario_id,
)

_GENERATED_NOTE = (
    "<!-- generated by specleft discover -- review before promoting to "
    ".specleft/specs/ -->"
)


def generate_draft_specs(
    draft_features: list[DraftFeature],
    output_dir: Path,
    dry_run: bool = False,
    overwrite: bool = False,
) -> list[Path]:
    """Write draft specs and return written paths (or would-be paths in dry-run)."""
    if not dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)

    output_paths: list[Path] = []
    for feature in draft_features:
        feature_id = _resolve_feature_id(feature)
        feature_path = output_dir / f"{feature_id}.md"

        if feature_path.exists() and not overwrite:
            continue

        output_paths.append(feature_path)
        if dry_run:
            continue

        feature_path.write_text(_render_feature(feature))

    return output_paths


def _resolve_feature_id(feature: DraftFeature) -> str:
    candidate = feature.feature_id.strip()
    if not candidate:
        candidate = generate_feature_id(feature.name)

    try:
        validate_feature_id(candidate)
        return candidate
    except ValueError:
        fallback = generate_feature_id(feature.name)
        validate_feature_id(fallback)
        return fallback


def _resolve_scenario_id(scenario: DraftScenario) -> str:
    scenario_id = generate_scenario_id(scenario.title)
    validate_scenario_id(scenario_id)
    return scenario_id


def _render_feature(feature: DraftFeature) -> str:
    lines: list[str] = [
        f"# Feature: {feature.name}",
        _GENERATED_NOTE,
        "",
        "## Scenarios",
    ]

    for scenario in feature.scenarios:
        scenario_id = _resolve_scenario_id(scenario)
        steps = _validate_steps(scenario)

        lines.extend(
            [
                "",
                f"### Scenario: {scenario_id}",
                f"priority: {scenario.priority}",
                "",
            ]
        )

        source_line = _source_line(scenario)
        if source_line is not None:
            lines.append(f"<!-- source: {source_line} -->")

        lines.extend(_format_steps(steps))

    lines.append("")
    return "\n".join(lines)


def _validate_steps(scenario: DraftScenario) -> list[SpecStep]:
    if len(scenario.steps) != 3:
        raise ValueError(
            f"Scenario '{scenario.title}' must have exactly 3 steps, got "
            f"{len(scenario.steps)}"
        )
    return scenario.steps


def _source_line(scenario: DraftScenario) -> str | None:
    if not scenario.source_items:
        return None

    source = scenario.source_items[0]
    if source.file_path is None:
        return None

    location = source.file_path.as_posix()
    if source.line_number is not None:
        location = f"{location}:{source.line_number}"
    return location


def _format_steps(steps: list[SpecStep]) -> list[str]:
    return [f"- {step.type.value.capitalize()} {step.description}" for step in steps]
