# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 SpecLeft Contributors

"""Tests for discovery draft spec markdown writing."""

from __future__ import annotations

import re
import shutil
from pathlib import Path

import pytest

from specleft.discovery.models import (
    TestFunctionMeta as DiscoveryTestFunctionMeta,
    DiscoveredItem,
    DraftFeature,
    DraftScenario,
    ItemKind,
    SupportedLanguage,
)
from specleft.discovery.spec_writer import generate_draft_specs
from specleft.discovery.traceability import TraceabilityLink
from specleft.parser import SpecParser
from specleft.schema import SpecStep, SpecsConfig, StepType
from specleft.utils.feature_writer import validate_feature_id, validate_scenario_id


def _source_item(path: Path, line_number: int = 14) -> DiscoveredItem:
    return DiscoveredItem(
        kind=ItemKind.TEST_FUNCTION,
        name="test_valid_credentials",
        file_path=path,
        line_number=line_number,
        language=SupportedLanguage.PYTHON,
        raw_text=None,
        metadata=DiscoveryTestFunctionMeta(framework="pytest").model_dump(),
        confidence=0.9,
    )


def _draft_feature(
    *,
    feature_id: str = "user-authentication",
    scenario_title: str = "valid-credentials",
    steps: list[SpecStep] | None = None,
) -> DraftFeature:
    scenario_steps = steps or [
        SpecStep(type=StepType.GIVEN, description="a user with valid credentials"),
        SpecStep(type=StepType.WHEN, description="they attempt to login"),
        SpecStep(type=StepType.THEN, description="they should be authenticated"),
    ]
    source = _source_item(Path("tests/auth/test_login.py"))
    scenario = DraftScenario(
        title=scenario_title,
        priority="medium",
        steps=scenario_steps,
        source_items=[source],
    )
    return DraftFeature(
        feature_id=feature_id,
        name="User Authentication",
        scenarios=[scenario],
        source_items=[source],
        confidence=0.8,
    )


def test_generate_draft_specs_dry_run_returns_paths_without_writing(
    tmp_path: Path,
) -> None:
    output_dir = tmp_path / ".specleft" / "specs" / "_discovered"

    paths = generate_draft_specs([_draft_feature()], output_dir, dry_run=True)

    assert paths == [output_dir / "user-authentication.md"]
    assert not output_dir.exists()


def test_generate_draft_specs_writes_parser_compatible_markdown(tmp_path: Path) -> None:
    output_dir = tmp_path / ".specleft" / "specs" / "_discovered"
    promoted_dir = tmp_path / ".specleft" / "specs"
    feature = _draft_feature()

    written_paths = generate_draft_specs([feature], output_dir)
    assert written_paths == [output_dir / "user-authentication.md"]
    assert written_paths[0].exists()

    content = written_paths[0].read_text()
    assert "<!-- generated by specleft discover" in content
    assert "<!-- source: tests/auth/test_login.py:14 -->" in content
    assert content.count("\n- Given ") == 1
    assert content.count("\n- When ") == 1
    assert content.count("\n- Then ") == 1

    shutil.copy2(written_paths[0], promoted_dir / written_paths[0].name)
    parser = SpecParser()
    parsed = parser.parse_directory(promoted_dir)

    assert len(parsed.features) == 1
    scenario = parsed.features[0].stories[0].scenarios[0]
    assert scenario.scenario_id == "valid-credentials"
    assert len(scenario.steps) == 3

    validate_feature_id(written_paths[0].stem)
    scenario_ids = re.findall(r"^### Scenario:\s*([a-z0-9-]+)$", content, re.MULTILINE)
    for scenario_id in scenario_ids:
        validate_scenario_id(scenario_id)


def test_generate_draft_specs_writes_linked_tests_frontmatter(tmp_path: Path) -> None:
    output_dir = tmp_path / ".specleft" / "specs" / "_discovered"
    feature = _draft_feature()
    links = [
        TraceabilityLink(
            test_file=Path("tests/test_user_authentication.py"),
            test_function="test_valid_credentials",
            spec_file=tmp_path / ".specleft" / "specs" / "user-authentication.md",
            scenario_id="valid-credentials",
            match_kind="both",
            confidence=0.9,
        )
    ]

    written_paths = generate_draft_specs(
        [feature], output_dir, traceability_links=links
    )
    content = written_paths[0].read_text()

    assert "linked_tests:" in content
    assert "file: tests/test_user_authentication.py" in content
    assert "function: test_valid_credentials" in content
    assert "confidence: 0.9" in content


def test_existing_file_is_not_overwritten_by_default(tmp_path: Path) -> None:
    output_dir = tmp_path / "out"
    output_dir.mkdir(parents=True)
    output_file = output_dir / "user-authentication.md"
    output_file.write_text("original-content")

    paths = generate_draft_specs([_draft_feature()], output_dir, overwrite=False)

    assert paths == []
    assert output_file.read_text() == "original-content"


def test_overwrite_replaces_existing_file_when_enabled(tmp_path: Path) -> None:
    output_dir = tmp_path / "out"
    output_dir.mkdir(parents=True)
    output_file = output_dir / "user-authentication.md"
    output_file.write_text("original-content")

    paths = generate_draft_specs([_draft_feature()], output_dir, overwrite=True)

    assert paths == [output_file]
    updated = output_file.read_text()
    assert "original-content" not in updated
    assert "### Scenario: valid-credentials" in updated


def test_generate_draft_specs_requires_three_steps_per_scenario(tmp_path: Path) -> None:
    output_dir = tmp_path / "out"
    invalid_steps = [
        SpecStep(type=StepType.GIVEN, description="a user exists"),
        SpecStep(type=StepType.WHEN, description="a request is sent"),
    ]
    feature = _draft_feature(steps=invalid_steps)

    with pytest.raises(ValueError, match="must have exactly 3 steps"):
        generate_draft_specs([feature], output_dir)


def test_specs_config_skips_underscore_discovery_directory(tmp_path: Path) -> None:
    specs_dir = tmp_path / ".specleft" / "specs"
    specs_dir.mkdir(parents=True)

    (specs_dir / "auth.md").write_text(
        "# Feature: Authentication\n"
        "\n"
        "## Scenarios\n"
        "\n"
        "### Scenario: sign-in\n"
        "priority: medium\n"
        "\n"
        "- Given a valid account\n"
        "- When credentials are submitted\n"
        "- Then sign-in succeeds\n"
    )

    discovered_dir = specs_dir / "_discovered"
    discovered_dir.mkdir()
    (discovered_dir / "payments.md").write_text(
        "# Feature: Payments\n"
        "\n"
        "## Scenarios\n"
        "\n"
        "### Scenario: refund\n"
        "priority: medium\n"
        "\n"
        "- Given a paid invoice\n"
        "- When a refund is requested\n"
        "- Then funds are returned\n"
    )

    config = SpecsConfig.from_directory(specs_dir)

    assert len(config.features) == 1
    assert config.features[0].feature_id == "auth"
